// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  
  apoDocsSidebar: [
    // {
    //   type: 'category',
    //   label: 'About APO',
    //   link: {
    //     type: 'generated-index',
    //   },
    //   collapsed: false,
    //   items: [
    //     'About APO/What is APO',
    //     'About APO/Architecture',
    //   ],
    // },
    'Quick Start',
    {
      type: 'category',
      label: 'Installation',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'Installation/APO Server',
        'Installation/APO OneAgent',
        {
          type: 'category',
          label: 'Advanced',
          link: {
            type: 'generated-index',
          },
          items: [
            'Installation/Advanced/Integrate with Existing Clickhouse',
            'Installation/Advanced/Integrate with Existing VictoriaMetrics',
            'Installation/Advanced/Replace OneAgent Otel Probe with Custom Tracing Probe',
          ],
        },
        {
          type: 'category',
          label: 'Additional Use Cases',
          link: {
            type: 'generated-index',
          },
          items: [
            'Installation/Additional Use Cases/Independent Logging Module',
            'Installation/Additional Use Cases/Independent Metrics Module',
            'Installation/Additional Use Cases/Independent Trace Module',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Distibuted Tracing',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'Distibuted Tracing/Modify Automatic Injection Scope',
      ],
    },
    {
      type: 'category',
      label: 'Logs Monitoring',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'Logs Monitoring/Configure Log Parsing Rules',
        'Logs Monitoring/Full Log Collection',
        'Logs Monitoring/Fault Log Collection',
        'Logs Monitoring/Nginx Log Collection',
      ],
    },
    {
      type: 'category',
      label: 'Metrics Monitoring',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'Metrics Monitoring/Elasticsearch',
        'Metrics Monitoring/Kafka',
        'Metrics Monitoring/MySQL',
        'Metrics Monitoring/RabbitMQ',
        'Metrics Monitoring/Redis',
        'Metrics Monitoring/More',
      ],
    },
    {
      type: 'category',
      label: 'Alerting',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'Alerting/Configure Alert Rules',
      ],
    },
    // {
    //   type: 'category',
    //   label: 'FAQ',
    //   link: {
    //     type: 'generated-index',
    //   },
    //   items: [
    //     'FAQ/FAQTest',
    //   ],
    // },
    {
      type: 'category',
      label: 'Troubleshooting',
      link: {
        type: 'generated-index',
      },
      items: [
        'Troubleshooting/Service Overview No Data',
        'Troubleshooting/eBPF-Agent Unready Issue',
        'Troubleshooting/Grafana-Beyla Unready Issue',
        'Troubleshooting/Cloud provider cluster failed to create the database',
      ],
    },
  ],
};

export default sidebars;
