// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  
  apoDocsSidebar: [
    {
      type: 'category',
      label: 'About APO',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'About APO/Introduction to APO',
        'About APO/APO Architecture',
      ],
    },
    {
      type: 'category',
      label: 'Quick Start Guide',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: ['Quick Start Guide/Quick Start'],
    },
    {
      type: 'category',
      label: 'Installation',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'Installation/Install APO Server',
        'Installation/Install APO OneAgent',
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'Configuration/Configuration external Database',
      ],
    },
    {
      type: 'category',
      label: 'Operations and Troubleshooting',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'Operations and Troubleshooting/APO Service Overview No Data Troubleshooting',
        {
          type: 'category',
          label: 'FAQ',
          link: {
            type: 'generated-index',
          },
          items: [
            'Operations and Troubleshooting/FAQ/FAQTest',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
